// <auto-generated />
using System;
using System.Collections.Generic;
using AdminPlatform.Modules.Seo.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdminPlatform.Modules.Seo.Infrastructure.Migrations
{
    [DbContext(typeof(SeoDbContext))]
    partial class SeoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("seo")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdminPlatform.Modules.Seo.Domain.SeoSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DefaultDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("default_description");

                    b.Property<string>("DefaultOgImageMediaId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("default_og_image_media_id");

                    b.Property<bool>("DefaultRobotsFollow")
                        .HasColumnType("boolean")
                        .HasColumnName("default_robots_follow");

                    b.Property<bool>("DefaultRobotsIndex")
                        .HasColumnType("boolean")
                        .HasColumnName("default_robots_index");

                    b.Property<string>("DefaultTitleTemplate")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("default_title_template");

                    b.Property<List<string>>("RobotsDisallowPaths")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("robots_disallow_paths");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("TwitterCreator")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("twitter_creator");

                    b.Property<string>("TwitterSite")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("twitter_site");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_seo_settings");

                    b.ToTable("seo_settings", "seo");
                });
#pragma warning restore 612, 618
        }
    }
}
