// <auto-generated />
using System;
using AdminPlatform.Modules.Sales.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdminPlatform.Modules.Sales.Infrastructure.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    [Migration("20261003184428_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sales")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdminPlatform.Modules.Sales.Domain.DeliveryMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseFee")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("base_fee");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<int?>("EstimatedMaxMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_max_minutes");

                    b.Property<int?>("EstimatedMinMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_min_minutes");

                    b.Property<decimal?>("FreeShippingThreshold")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("free_shipping_threshold");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PickupAddress")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("pickup_address");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_delivery_methods");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_delivery_methods_code");

                    b.HasIndex("IsActive", "DisplayOrder")
                        .HasDatabaseName("ix_delivery_methods_is_active_display_order");

                    b.ToTable("delivery_methods", "sales", t =>
                        {
                            t.HasCheckConstraint("ck_delivery_methods_base_fee_non_negative", "base_fee >= 0");

                            t.HasCheckConstraint("ck_delivery_methods_threshold_non_negative", "free_shipping_threshold IS NULL OR free_shipping_threshold >= 0");
                        });
                });

            modelBuilder.Entity("AdminPlatform.Modules.Sales.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("customer_note");

                    b.Property<string>("DeliveryAddressSnapshot")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("delivery_address_snapshot");

                    b.Property<decimal>("DeliveryFee")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("delivery_fee");

                    b.Property<string>("DeliveryMethodCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("delivery_method_code");

                    b.Property<string>("DeliveryMethodLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("delivery_method_label");

                    b.Property<decimal>("Discount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("discount");

                    b.Property<string>("DiscountCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("discount_code");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<bool>("IsPickup")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pickup");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("order_code");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("order_status");

                    b.Property<string>("PaymentMethodCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payment_method_code");

                    b.Property<string>("PaymentMethodLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("payment_method_label");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("payment_status");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<Guid?>("PromotionId")
                        .HasColumnType("uuid")
                        .HasColumnName("promotion_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<decimal>("ShippingDiscount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("shipping_discount");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<bool>("WantsUtensils")
                        .HasColumnType("boolean")
                        .HasColumnName("wants_utensils");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_orders_created_at_utc");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_orders_customer_id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("OrderCode")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_order_code");

                    b.HasIndex("Phone")
                        .HasDatabaseName("ix_orders_phone");

                    b.HasIndex("OrderStatus", "CreatedAtUtc")
                        .HasDatabaseName("ix_orders_order_status_created_at_utc");

                    b.ToTable("orders", "sales", t =>
                        {
                            t.HasCheckConstraint("ck_orders_amounts_non_negative", "subtotal >= 0 AND discount >= 0 AND shipping_discount >= 0 AND delivery_fee >= 0 AND total_amount >= 0");

                            t.HasCheckConstraint("ck_orders_total_matches", "total_amount = subtotal - discount + delivery_fee - shipping_discount");
                        });
                });

            modelBuilder.Entity("AdminPlatform.Modules.Sales.Domain.OrderCodeCounter", b =>
                {
                    b.Property<string>("CounterKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("counter_key");

                    b.Property<int>("LastNumber")
                        .HasColumnType("integer")
                        .HasColumnName("last_number");

                    b.HasKey("CounterKey")
                        .HasName("pk_order_code_counters");

                    b.ToTable("order_code_counters", "sales");
                });

            modelBuilder.Entity("AdminPlatform.Modules.Sales.Domain.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ItemNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("item_note");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("line_total");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductImageMediaId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_image_media_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_items_order_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_order_items_product_id");

                    b.ToTable("order_items", "sales", t =>
                        {
                            t.HasCheckConstraint("ck_order_items_amounts_non_negative", "unit_price >= 0 AND line_total >= 0");

                            t.HasCheckConstraint("ck_order_items_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("AdminPlatform.Modules.Sales.Domain.OrderItemModifier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("group_name");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("option_id");

                    b.Property<string>("OptionLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("option_label");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_item_id");

                    b.Property<decimal>("PriceAdjustment")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price_adjustment");

                    b.HasKey("Id")
                        .HasName("pk_order_item_modifiers");

                    b.HasIndex("OrderItemId")
                        .HasDatabaseName("ix_order_item_modifiers_order_item_id");

                    b.ToTable("order_item_modifiers", "sales");
                });

            modelBuilder.Entity("AdminPlatform.Modules.Sales.Domain.OrderOptionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SelectionType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("selection_type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_order_option_groups");

                    b.ToTable("order_option_groups", "sales");
                });

            modelBuilder.Entity("AdminPlatform.Modules.Sales.Domain.OrderOptionSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("group_name");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("option_id");

                    b.Property<string>("OptionLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("option_label");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<decimal>("PriceAdjustment")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price_adjustment");

                    b.HasKey("Id")
                        .HasName("pk_order_option_selections");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_option_selections_order_id");

                    b.ToTable("order_option_selections", "sales");
                });

            modelBuilder.Entity("AdminPlatform.Modules.Sales.Domain.OrderOptionValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<Guid>("OrderOptionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_option_group_id");

                    b.Property<decimal>("PriceAdjustment")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price_adjustment");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_order_option_values");

                    b.HasIndex("OrderOptionGroupId")
                        .HasDatabaseName("ix_order_option_values_order_option_group_id");

                    b.ToTable("order_option_values", "sales");
                });

            modelBuilder.Entity("AdminPlatform.Modules.Sales.Domain.OrderSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("OrderCodeDateFormat")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("order_code_date_format");

                    b.Property<string>("OrderCodePrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("order_code_prefix");

                    b.Property<int>("OrderCodeSequenceLength")
                        .HasColumnType("integer")
                        .HasColumnName("order_code_sequence_length");

                    b.Property<int>("PaymentSessionMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("payment_session_minutes");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_order_settings");

                    b.ToTable("order_settings", "sales", t =>
                        {
                            t.HasCheckConstraint("ck_order_settings_sequence_length", "order_code_sequence_length BETWEEN 3 AND 8");

                            t.HasCheckConstraint("ck_order_settings_session_minutes", "payment_session_minutes BETWEEN 5 AND 240");
                        });
                });

            modelBuilder.Entity("AdminPlatform.Modules.Sales.Domain.OrderStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at_utc");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("changed_by");

                    b.Property<Guid?>("ChangedById")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_id");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("from_status");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_order_status_histories");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_status_histories_order_id");

                    b.ToTable("order_status_histories", "sales");
                });

            modelBuilder.Entity("AdminPlatform.Modules.Sales.Domain.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at_utc");

                    b.Property<string>("Gateway")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("gateway");

                    b.Property<string>("GatewayReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("gateway_reference");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("order_code");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at_utc");

                    b.Property<string>("PaymentMethodCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payment_method_code");

                    b.Property<string>("PaymentMethodLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("payment_method_label");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("transaction_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_order_id");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_payments_status_created_at_utc");

                    b.ToTable("payments", "sales", t =>
                        {
                            t.HasCheckConstraint("ck_payments_amount_non_negative", "amount >= 0");
                        });
                });

            modelBuilder.Entity("AdminPlatform.Modules.Sales.Domain.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BankAccountHolder")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bank_account_holder");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bank_account_number");

                    b.Property<string>("BankBranch")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bank_branch");

                    b.Property<string>("BankName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bank_name");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Gateway")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("gateway");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("group");

                    b.Property<string>("IconMediaId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("icon_media_id");

                    b.Property<string>("Instructions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("instructions");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<decimal?>("MaxOrderAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("max_order_amount");

                    b.Property<decimal?>("MinOrderAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("min_order_amount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_payment_methods");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_payment_methods_code");

                    b.HasIndex("IsActive", "DisplayOrder")
                        .HasDatabaseName("ix_payment_methods_is_active_display_order");

                    b.ToTable("payment_methods", "sales", t =>
                        {
                            t.HasCheckConstraint("ck_payment_methods_max_non_negative", "max_order_amount IS NULL OR max_order_amount >= 0");

                            t.HasCheckConstraint("ck_payment_methods_min_non_negative", "min_order_amount IS NULL OR min_order_amount >= 0");
                        });
                });

            modelBuilder.Entity("AdminPlatform.Modules.Sales.Domain.PaymentSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BankAccountHolder")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bank_account_holder");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bank_account_number");

                    b.Property<string>("BankName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bank_name");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("customer_note");

                    b.Property<string>("DeliveryAddressSnapshot")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("delivery_address_snapshot");

                    b.Property<string>("DeliveryMethodCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("delivery_method_code");

                    b.Property<string>("DeliveryMethodLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("delivery_method_label");

                    b.Property<decimal>("Discount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("discount");

                    b.Property<string>("DiscountCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("discount_code");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<bool>("IsPickup")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pickup");

                    b.Property<string>("LinesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("lines_json");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("order_code");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("PaymentMethodCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payment_method_code");

                    b.Property<string>("PaymentMethodLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("payment_method_label");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<Guid?>("PromotionId")
                        .HasColumnType("uuid")
                        .HasColumnName("promotion_id");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reference_code");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("request_json");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resolution_note");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<decimal>("ShippingDiscount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("shipping_discount");

                    b.Property<decimal>("ShippingFee")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("shipping_fee");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<bool>("WantsUtensils")
                        .HasColumnType("boolean")
                        .HasColumnName("wants_utensils");

                    b.HasKey("Id")
                        .HasName("pk_payment_sessions");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_payment_sessions_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("ReferenceCode")
                        .IsUnique()
                        .HasDatabaseName("ix_payment_sessions_reference_code");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_payment_sessions_status_created_at_utc");

                    b.ToTable("payment_sessions", "sales", t =>
                        {
                            t.HasCheckConstraint("ck_payment_sessions_total_non_negative", "total_amount >= 0");
                        });
                });

            modelBuilder.Entity("AdminPlatform.Modules.Sales.Domain.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("action");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("changed_by");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Gateway")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("gateway");

                    b.Property<string>("GatewayReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("gateway_reference");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("result");

                    b.HasKey("Id")
                        .HasName("pk_payment_transactions");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("ix_payment_transactions_payment_id");

                    b.ToTable("payment_transactions", "sales");
                });

            modelBuilder.Entity("AdminPlatform.Modules.Sales.Domain.OrderItem", b =>
                {
                    b.HasOne("AdminPlatform.Modules.Sales.Domain.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_orders_order_id");
                });

            modelBuilder.Entity("AdminPlatform.Modules.Sales.Domain.OrderItemModifier", b =>
                {
                    b.HasOne("AdminPlatform.Modules.Sales.Domain.OrderItem", null)
                        .WithMany("Modifiers")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_item_modifiers_order_items_order_item_id");
                });

            modelBuilder.Entity("AdminPlatform.Modules.Sales.Domain.OrderOptionSelection", b =>
                {
                    b.HasOne("AdminPlatform.Modules.Sales.Domain.Order", null)
                        .WithMany("OptionSelections")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_option_selections_orders_order_id");
                });

            modelBuilder.Entity("AdminPlatform.Modules.Sales.Domain.OrderOptionValue", b =>
                {
                    b.HasOne("AdminPlatform.Modules.Sales.Domain.OrderOptionGroup", null)
                        .WithMany("Values")
                        .HasForeignKey("OrderOptionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_option_values_order_option_groups_order_option_group_");
                });

            modelBuilder.Entity("AdminPlatform.Modules.Sales.Domain.OrderStatusHistory", b =>
                {
                    b.HasOne("AdminPlatform.Modules.Sales.Domain.Order", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_status_histories_orders_order_id");
                });

            modelBuilder.Entity("AdminPlatform.Modules.Sales.Domain.Payment", b =>
                {
                    b.HasOne("AdminPlatform.Modules.Sales.Domain.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_orders_order_id");
                });

            modelBuilder.Entity("AdminPlatform.Modules.Sales.Domain.PaymentTransaction", b =>
                {
                    b.HasOne("AdminPlatform.Modules.Sales.Domain.Payment", null)
                        .WithMany("Transactions")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payment_transactions_payments_payment_id");
                });

            modelBuilder.Entity("AdminPlatform.Modules.Sales.Domain.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("OptionSelections");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("AdminPlatform.Modules.Sales.Domain.OrderItem", b =>
                {
                    b.Navigation("Modifiers");
                });

            modelBuilder.Entity("AdminPlatform.Modules.Sales.Domain.OrderOptionGroup", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("AdminPlatform.Modules.Sales.Domain.Payment", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
