using AdminPlatform.Modules.Sales.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AdminPlatform.Modules.Sales.Infrastructure.Configurations;

internal sealed class DeliveryMethodConfiguration : IEntityTypeConfiguration<DeliveryMethod>
{
    public void Configure(EntityTypeBuilder<DeliveryMethod> builder)
    {
        builder.ToTable("delivery_methods", table =>
        {
            table.HasCheckConstraint("ck_delivery_methods_base_fee_non_negative", "base_fee >= 0");
            table.HasCheckConstraint("ck_delivery_methods_threshold_non_negative", "free_shipping_threshold IS NULL OR free_shipping_threshold >= 0");
        });
        builder.HasKey(m => m.Id);
        builder.Property(m => m.RowVersion).IsRowVersion();

        builder.Property(m => m.Code).HasMaxLength(DeliveryMethod.MaxCodeLength).IsRequired();
        builder.HasIndex(m => m.Code).IsUnique();
        builder.Property(m => m.Name).HasMaxLength(DeliveryMethod.MaxNameLength).IsRequired();
        builder.Property(m => m.Description).HasMaxLength(DeliveryMethod.MaxTextLength);
        builder.Property(m => m.Type).HasConversion(new EnumWireConverter<DeliveryMethodType>()).HasMaxLength(16).IsRequired();
        builder.Property(m => m.BaseFee).HasPrecision(12, 2);
        builder.Property(m => m.FreeShippingThreshold).HasPrecision(12, 2);
        builder.Property(m => m.PickupAddress).HasMaxLength(DeliveryMethod.MaxTextLength);
        builder.HasIndex(m => new { m.IsActive, m.DisplayOrder });
    }
}

internal sealed class PaymentMethodConfiguration : IEntityTypeConfiguration<PaymentMethod>
{
    public void Configure(EntityTypeBuilder<PaymentMethod> builder)
    {
        builder.ToTable("payment_methods", table =>
        {
            table.HasCheckConstraint("ck_payment_methods_min_non_negative", "min_order_amount IS NULL OR min_order_amount >= 0");
            table.HasCheckConstraint("ck_payment_methods_max_non_negative", "max_order_amount IS NULL OR max_order_amount >= 0");
        });
        builder.HasKey(m => m.Id);
        builder.Property(m => m.RowVersion).IsRowVersion();

        builder.Property(m => m.Code).HasMaxLength(PaymentMethod.MaxCodeLength).IsRequired();
        builder.HasIndex(m => m.Code).IsUnique();
        builder.Property(m => m.Name).HasMaxLength(PaymentMethod.MaxNameLength).IsRequired();
        builder.Property(m => m.Description).HasMaxLength(PaymentMethod.MaxTextLength);
        builder.Property(m => m.IconMediaId).HasMaxLength(PaymentMethod.MaxShortTextLength);
        builder.Property(m => m.Group).HasConversion(new EnumWireConverter<PaymentMethodGroup>()).HasMaxLength(16).IsRequired();
        builder.Property(m => m.Gateway).HasMaxLength(PaymentMethod.MaxShortTextLength);
        builder.Property(m => m.Instructions).HasMaxLength(PaymentMethod.MaxTextLength);
        builder.Property(m => m.BankName).HasMaxLength(PaymentMethod.MaxShortTextLength);
        builder.Property(m => m.BankAccountNumber).HasMaxLength(PaymentMethod.MaxShortTextLength);
        builder.Property(m => m.BankAccountHolder).HasMaxLength(PaymentMethod.MaxShortTextLength);
        builder.Property(m => m.BankBranch).HasMaxLength(PaymentMethod.MaxShortTextLength);
        builder.Property(m => m.MinOrderAmount).HasPrecision(12, 2);
        builder.Property(m => m.MaxOrderAmount).HasPrecision(12, 2);
        builder.HasIndex(m => new { m.IsActive, m.DisplayOrder });
    }
}

internal sealed class OrderOptionGroupConfiguration : IEntityTypeConfiguration<OrderOptionGroup>
{
    public void Configure(EntityTypeBuilder<OrderOptionGroup> builder)
    {
        builder.ToTable("order_option_groups");
        builder.HasKey(g => g.Id);
        builder.Property(g => g.RowVersion).IsRowVersion();

        builder.Property(g => g.Name).HasMaxLength(OrderOptionGroup.MaxNameLength).IsRequired();
        builder.Property(g => g.SelectionType).HasConversion(new EnumWireConverter<OptionSelectionType>()).HasMaxLength(16).IsRequired();

        builder.HasMany(g => g.Values)
            .WithOne()
            .HasForeignKey(v => v.OrderOptionGroupId)
            .OnDelete(DeleteBehavior.Cascade);
        builder.Navigation(g => g.Values).HasField("_values");
    }
}

internal sealed class OrderOptionValueConfiguration : IEntityTypeConfiguration<OrderOptionValue>
{
    public void Configure(EntityTypeBuilder<OrderOptionValue> builder)
    {
        builder.ToTable("order_option_values");
        builder.HasKey(v => v.Id);
        // Ids are generated by the domain; without this EF treats a value added to a loaded group (non-default
        // key) as an existing row and issues an UPDATE instead of an INSERT.
        builder.Property(v => v.Id).ValueGeneratedNever();

        builder.Property(v => v.Label).HasMaxLength(200).IsRequired();
        builder.Property(v => v.PriceAdjustment).HasPrecision(12, 2);
        builder.HasIndex(v => v.OrderOptionGroupId);
    }
}

internal sealed class OrderSettingsConfiguration : IEntityTypeConfiguration<OrderSettings>
{
    public void Configure(EntityTypeBuilder<OrderSettings> builder)
    {
        builder.ToTable("order_settings", table =>
        {
            table.HasCheckConstraint("ck_order_settings_sequence_length", "order_code_sequence_length BETWEEN 3 AND 8");
            table.HasCheckConstraint("ck_order_settings_session_minutes", "payment_session_minutes BETWEEN 5 AND 240");
        });
        builder.HasKey(s => s.Id);
        builder.Property(s => s.RowVersion).IsRowVersion();

        builder.Property(s => s.OrderCodePrefix).HasMaxLength(OrderSettings.MaxPrefixLength).IsRequired();
        builder.Property(s => s.OrderCodeDateFormat).HasMaxLength(16).IsRequired();
    }
}
