using AdminPlatform.Modules.Sales.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AdminPlatform.Modules.Sales.Infrastructure.Configurations;

internal sealed class OrderConfiguration : IEntityTypeConfiguration<Order>
{
    public void Configure(EntityTypeBuilder<Order> builder)
    {
        builder.ToTable("orders", table =>
        {
            table.HasCheckConstraint("ck_orders_amounts_non_negative",
                "subtotal >= 0 AND discount >= 0 AND shipping_discount >= 0 AND delivery_fee >= 0 AND total_amount >= 0");
            table.HasCheckConstraint("ck_orders_total_matches",
                "total_amount = subtotal - discount + delivery_fee - shipping_discount");
        });
        builder.HasKey(o => o.Id);
        builder.Property(o => o.RowVersion).IsRowVersion();

        builder.Property(o => o.OrderCode).HasMaxLength(64).IsRequired();
        builder.HasIndex(o => o.OrderCode).IsUnique();
        builder.Property(o => o.IdempotencyKey).HasMaxLength(100);
        builder.HasIndex(o => o.IdempotencyKey).IsUnique().HasFilter("idempotency_key IS NOT NULL");

        builder.Property(o => o.CustomerName).HasMaxLength(Order.MaxNameLength).IsRequired();
        builder.Property(o => o.Phone).HasMaxLength(20).IsRequired();
        builder.Property(o => o.Email).HasMaxLength(Order.MaxEmailLength);
        builder.Property(o => o.DeliveryAddressSnapshot).HasMaxLength(Order.MaxAddressLength).IsRequired();
        builder.Property(o => o.PaymentMethodCode).HasMaxLength(PaymentMethod.MaxCodeLength).IsRequired();
        builder.Property(o => o.PaymentMethodLabel).HasMaxLength(PaymentMethod.MaxNameLength).IsRequired();
        builder.Property(o => o.DeliveryMethodCode).HasMaxLength(DeliveryMethod.MaxCodeLength).IsRequired();
        builder.Property(o => o.DeliveryMethodLabel).HasMaxLength(DeliveryMethod.MaxNameLength).IsRequired();

        builder.Property(o => o.Subtotal).HasPrecision(12, 2);
        builder.Property(o => o.Discount).HasPrecision(12, 2);
        builder.Property(o => o.DiscountCode).HasMaxLength(64);
        builder.Property(o => o.ShippingDiscount).HasPrecision(12, 2);
        builder.Property(o => o.DeliveryFee).HasPrecision(12, 2);
        builder.Property(o => o.TotalAmount).HasPrecision(12, 2);

        builder.Property(o => o.OrderStatus).HasConversion(new EnumWireConverter<OrderStatus>()).HasMaxLength(16).IsRequired();
        builder.Property(o => o.PaymentStatus).HasConversion(new EnumWireConverter<PaymentStatus>()).HasMaxLength(16).IsRequired();
        builder.Property(o => o.CustomerNote).HasMaxLength(Order.MaxNoteLength);

        builder.HasIndex(o => o.CustomerId);
        builder.HasIndex(o => o.Phone);
        builder.HasIndex(o => o.CreatedAtUtc);
        builder.HasIndex(o => new { o.OrderStatus, o.CreatedAtUtc });

        builder.HasMany(o => o.Items).WithOne().HasForeignKey(i => i.OrderId).OnDelete(DeleteBehavior.Cascade);
        builder.Navigation(o => o.Items).HasField("_items");
        builder.HasMany(o => o.OptionSelections).WithOne().HasForeignKey(s => s.OrderId).OnDelete(DeleteBehavior.Cascade);
        builder.Navigation(o => o.OptionSelections).HasField("_optionSelections");
        builder.HasMany(o => o.StatusHistory).WithOne().HasForeignKey(h => h.OrderId).OnDelete(DeleteBehavior.Cascade);
        builder.Navigation(o => o.StatusHistory).HasField("_statusHistory");
    }
}

internal sealed class OrderItemConfiguration : IEntityTypeConfiguration<OrderItem>
{
    public void Configure(EntityTypeBuilder<OrderItem> builder)
    {
        builder.ToTable("order_items", table =>
        {
            table.HasCheckConstraint("ck_order_items_quantity_positive", "quantity > 0");
            table.HasCheckConstraint("ck_order_items_amounts_non_negative", "unit_price >= 0 AND line_total >= 0");
        });
        builder.HasKey(i => i.Id);
        // Ids are generated by the domain, so EF must insert (not update) lines added to a loaded order.
        builder.Property(i => i.Id).ValueGeneratedNever();

        builder.Property(i => i.ProductName).HasMaxLength(200).IsRequired();
        builder.Property(i => i.ProductImageMediaId).HasMaxLength(200);
        builder.Property(i => i.UnitPrice).HasPrecision(12, 2);
        builder.Property(i => i.LineTotal).HasPrecision(12, 2);
        builder.Property(i => i.ItemNote).HasMaxLength(Order.MaxNoteLength);
        builder.HasIndex(i => i.OrderId);
        builder.HasIndex(i => i.ProductId);

        builder.HasMany(i => i.Modifiers).WithOne().HasForeignKey(m => m.OrderItemId).OnDelete(DeleteBehavior.Cascade);
        builder.Navigation(i => i.Modifiers).HasField("_modifiers");
    }
}

internal sealed class OrderItemModifierConfiguration : IEntityTypeConfiguration<OrderItemModifier>
{
    public void Configure(EntityTypeBuilder<OrderItemModifier> builder)
    {
        builder.ToTable("order_item_modifiers");
        builder.HasKey(m => m.Id);
        builder.Property(m => m.Id).ValueGeneratedNever();

        builder.Property(m => m.GroupName).HasMaxLength(200).IsRequired();
        builder.Property(m => m.OptionLabel).HasMaxLength(200).IsRequired();
        builder.Property(m => m.PriceAdjustment).HasPrecision(12, 2);
        builder.HasIndex(m => m.OrderItemId);
    }
}

internal sealed class OrderOptionSelectionConfiguration : IEntityTypeConfiguration<OrderOptionSelection>
{
    public void Configure(EntityTypeBuilder<OrderOptionSelection> builder)
    {
        builder.ToTable("order_option_selections");
        builder.HasKey(s => s.Id);
        builder.Property(s => s.Id).ValueGeneratedNever();

        builder.Property(s => s.GroupName).HasMaxLength(200).IsRequired();
        builder.Property(s => s.OptionLabel).HasMaxLength(200).IsRequired();
        builder.Property(s => s.PriceAdjustment).HasPrecision(12, 2);
        builder.HasIndex(s => s.OrderId);
    }
}

internal sealed class OrderStatusHistoryConfiguration : IEntityTypeConfiguration<OrderStatusHistory>
{
    public void Configure(EntityTypeBuilder<OrderStatusHistory> builder)
    {
        builder.ToTable("order_status_histories");
        builder.HasKey(h => h.Id);
        builder.Property(h => h.Id).ValueGeneratedNever();

        builder.Property(h => h.FromStatus).HasConversion(new EnumWireConverter<OrderStatus>()).HasMaxLength(16);
        builder.Property(h => h.ToStatus).HasConversion(new EnumWireConverter<OrderStatus>()).HasMaxLength(16).IsRequired();
        builder.Property(h => h.ChangedBy).HasMaxLength(320).IsRequired();
        builder.Property(h => h.Note).HasMaxLength(Order.MaxNoteLength);
        builder.HasIndex(h => h.OrderId);
    }
}

internal sealed class PaymentConfiguration : IEntityTypeConfiguration<Payment>
{
    public void Configure(EntityTypeBuilder<Payment> builder)
    {
        builder.ToTable("payments", table => table.HasCheckConstraint("ck_payments_amount_non_negative", "amount >= 0"));
        builder.HasKey(p => p.Id);
        builder.Property(p => p.RowVersion).IsRowVersion();

        builder.Property(p => p.OrderCode).HasMaxLength(64).IsRequired();
        builder.Property(p => p.PaymentMethodCode).HasMaxLength(PaymentMethod.MaxCodeLength).IsRequired();
        builder.Property(p => p.PaymentMethodLabel).HasMaxLength(PaymentMethod.MaxNameLength).IsRequired();
        builder.Property(p => p.Amount).HasPrecision(12, 2);
        builder.Property(p => p.Status).HasConversion(new EnumWireConverter<PaymentStatus>()).HasMaxLength(16).IsRequired();
        builder.Property(p => p.TransactionId).HasMaxLength(200);
        builder.Property(p => p.Gateway).HasMaxLength(200);
        builder.Property(p => p.GatewayReference).HasMaxLength(200);

        // One payment per order today; a unique index also guards against a double insert.
        builder.HasIndex(p => p.OrderId).IsUnique();
        builder.HasIndex(p => new { p.Status, p.CreatedAtUtc });

        builder.HasOne<Order>().WithMany().HasForeignKey(p => p.OrderId).OnDelete(DeleteBehavior.Cascade);
        builder.HasMany(p => p.Transactions).WithOne().HasForeignKey(t => t.PaymentId).OnDelete(DeleteBehavior.Cascade);
        builder.Navigation(p => p.Transactions).HasField("_transactions");
    }
}

internal sealed class PaymentTransactionConfiguration : IEntityTypeConfiguration<PaymentTransaction>
{
    public void Configure(EntityTypeBuilder<PaymentTransaction> builder)
    {
        builder.ToTable("payment_transactions");
        builder.HasKey(t => t.Id);
        builder.Property(t => t.Id).ValueGeneratedNever();

        builder.Property(t => t.Action).HasConversion(new EnumWireConverter<PaymentTransactionAction>()).HasMaxLength(16).IsRequired();
        builder.Property(t => t.Result).HasConversion(new EnumWireConverter<PaymentTransactionResult>()).HasMaxLength(16).IsRequired();
        builder.Property(t => t.Gateway).HasMaxLength(200);
        builder.Property(t => t.GatewayReference).HasMaxLength(200);
        builder.Property(t => t.Message).HasMaxLength(1000);
        builder.Property(t => t.ChangedBy).HasMaxLength(320).IsRequired();
        builder.HasIndex(t => t.PaymentId);
    }
}

internal sealed class PaymentSessionConfiguration : IEntityTypeConfiguration<PaymentSession>
{
    public void Configure(EntityTypeBuilder<PaymentSession> builder)
    {
        builder.ToTable("payment_sessions", table => table.HasCheckConstraint("ck_payment_sessions_total_non_negative", "total_amount >= 0"));
        builder.HasKey(s => s.Id);
        builder.Property(s => s.RowVersion).IsRowVersion();

        builder.Property(s => s.ReferenceCode).HasMaxLength(PaymentSession.MaxReferenceLength).IsRequired();
        builder.HasIndex(s => s.ReferenceCode).IsUnique();
        builder.Property(s => s.Status).HasConversion(new EnumWireConverter<PaymentSessionStatus>()).HasMaxLength(16).IsRequired();
        builder.Property(s => s.Channel).HasConversion(new EnumWireConverter<PaymentChannel>()).HasMaxLength(16).IsRequired();
        builder.Property(s => s.PaymentMethodCode).HasMaxLength(PaymentMethod.MaxCodeLength).IsRequired();
        builder.Property(s => s.PaymentMethodLabel).HasMaxLength(PaymentMethod.MaxNameLength).IsRequired();

        builder.Property(s => s.CustomerName).HasMaxLength(Order.MaxNameLength).IsRequired();
        builder.Property(s => s.Phone).HasMaxLength(20).IsRequired();
        builder.Property(s => s.Email).HasMaxLength(Order.MaxEmailLength);
        builder.Property(s => s.DeliveryMethodCode).HasMaxLength(DeliveryMethod.MaxCodeLength).IsRequired();
        builder.Property(s => s.DeliveryMethodLabel).HasMaxLength(DeliveryMethod.MaxNameLength).IsRequired();
        builder.Property(s => s.DeliveryAddressSnapshot).HasMaxLength(Order.MaxAddressLength).IsRequired();
        builder.Property(s => s.CustomerNote).HasMaxLength(Order.MaxNoteLength);

        builder.Property(s => s.Subtotal).HasPrecision(12, 2);
        builder.Property(s => s.ShippingFee).HasPrecision(12, 2);
        builder.Property(s => s.Discount).HasPrecision(12, 2);
        builder.Property(s => s.DiscountCode).HasMaxLength(64);
        builder.Property(s => s.ShippingDiscount).HasPrecision(12, 2);
        builder.Property(s => s.TotalAmount).HasPrecision(12, 2);

        builder.Property(s => s.BankName).HasMaxLength(PaymentMethod.MaxShortTextLength);
        builder.Property(s => s.BankAccountNumber).HasMaxLength(PaymentMethod.MaxShortTextLength);
        builder.Property(s => s.BankAccountHolder).HasMaxLength(PaymentMethod.MaxShortTextLength);

        builder.Property(s => s.IdempotencyKey).HasMaxLength(100);
        builder.HasIndex(s => s.IdempotencyKey).IsUnique().HasFilter("idempotency_key IS NOT NULL");
        builder.Property(s => s.RequestJson).HasColumnType("jsonb").IsRequired();
        builder.Property(s => s.LinesJson).HasColumnType("jsonb").IsRequired();
        builder.Property(s => s.OrderCode).HasMaxLength(64);
        builder.Property(s => s.ResolutionNote).HasMaxLength(1000);

        builder.HasIndex(s => new { s.Status, s.CreatedAtUtc });
    }
}
