using AdminPlatform.Modules.Catalog.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AdminPlatform.Modules.Catalog.Infrastructure.Configurations;

internal sealed class ModifierGroupConfiguration : IEntityTypeConfiguration<ModifierGroup>
{
    public void Configure(EntityTypeBuilder<ModifierGroup> builder)
    {
        builder.ToTable("modifier_groups");
        builder.HasKey(g => g.Id);
        builder.Property(g => g.RowVersion).IsRowVersion();

        builder.Property(g => g.Name).HasMaxLength(200).IsRequired();
        builder.Property(g => g.SelectionType).HasConversion<string>().HasMaxLength(16).IsRequired();

        builder.HasMany(g => g.Options)
            .WithOne()
            .HasForeignKey(o => o.ModifierGroupId)
            .OnDelete(DeleteBehavior.Cascade);
        builder.Navigation(g => g.Options).HasField("_options");
    }
}

internal sealed class ModifierOptionConfiguration : IEntityTypeConfiguration<ModifierOption>
{
    public void Configure(EntityTypeBuilder<ModifierOption> builder)
    {
        builder.ToTable("modifier_options");
        builder.HasKey(o => o.Id);
        // Ids are generated by the domain; without this EF treats a new option added to a loaded group
        // (non-default key) as an existing row and issues an UPDATE instead of an INSERT.
        builder.Property(o => o.Id).ValueGeneratedNever();

        builder.Property(o => o.Label).HasMaxLength(200).IsRequired();
        builder.Property(o => o.PriceAdjustment).HasPrecision(12, 2);
        builder.HasIndex(o => o.ModifierGroupId);
    }
}
