<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BuildingBlocks\AdminPlatform.SharedKernel\AdminPlatform.SharedKernel.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\AdminPlatform.Common\AdminPlatform.Common.csproj" />
    <ProjectReference Include="..\..\src\Modules\Identity\AdminPlatform.Modules.Identity\AdminPlatform.Modules.Identity.csproj" />
    <ProjectReference Include="..\..\src\Modules\AccessControl\AdminPlatform.Modules.AccessControl\AdminPlatform.Modules.AccessControl.csproj" />
    <ProjectReference Include="..\..\src\Modules\Organization\AdminPlatform.Modules.Organization\AdminPlatform.Modules.Organization.csproj" />
    <ProjectReference Include="..\..\src\Modules\Navigation\AdminPlatform.Modules.Navigation\AdminPlatform.Modules.Navigation.csproj" />
    <ProjectReference Include="..\..\src\Modules\Platform\AdminPlatform.Modules.Platform\AdminPlatform.Modules.Platform.csproj" />
  </ItemGroup>

</Project>
