// <auto-generated />
using System;
using AdminPlatform.Modules.Navigation.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdminPlatform.Modules.Navigation.Infrastructure.Migrations
{
    [DbContext(typeof(NavigationDbContext))]
    [Migration("20261004045653_UnifyNavigation")]
    partial class UnifyNavigation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("navigation")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdminPlatform.Modules.Navigation.Domain.NavigationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsGroup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_group");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid")
                        .HasColumnName("menu_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_navigation_items");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_navigation_items_parent_id");

                    b.HasIndex("MenuId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_navigation_items_menu_id_code");

                    b.HasIndex("MenuId", "ParentId", "SortOrder")
                        .HasDatabaseName("ix_navigation_items_menu_id_parent_id_sort_order");

                    b.ToTable("navigation_items", "navigation", t =>
                        {
                            t.HasCheckConstraint("ck_navigation_items_group_has_no_url", "is_group = false OR url IS NULL");

                            t.HasCheckConstraint("ck_navigation_items_not_own_parent", "parent_id IS NULL OR parent_id <> id");
                        });
                });

            modelBuilder.Entity("AdminPlatform.Modules.Navigation.Domain.NavigationItemPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("permission_code");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_navigation_item_permissions");

                    b.HasIndex("ItemId", "PermissionCode")
                        .IsUnique()
                        .HasDatabaseName("ix_navigation_item_permissions_item_id_permission_code");

                    b.ToTable("navigation_item_permissions", "navigation");
                });

            modelBuilder.Entity("AdminPlatform.Modules.Navigation.Domain.NavigationItemSiteDetail", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<bool>("OpenInNewTab")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("open_in_new_tab");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("target_type");

                    b.HasKey("ItemId")
                        .HasName("pk_navigation_item_site_details");

                    b.ToTable("navigation_item_site_details", "navigation");
                });

            modelBuilder.Entity("AdminPlatform.Modules.Navigation.Domain.NavigationMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("scope");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_navigation_menus");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_navigation_menus_code");

                    b.HasIndex("Scope", "Location")
                        .IsUnique()
                        .HasDatabaseName("ix_navigation_menus_scope_location");

                    b.ToTable("navigation_menus", "navigation", t =>
                        {
                            t.HasCheckConstraint("ck_navigation_menus_placement", "(scope = 'Admin' AND location = 'Sidebar') OR (scope = 'Site' AND location IN ('Header', 'Footer', 'Mobile'))");
                        });
                });

            modelBuilder.Entity("AdminPlatform.Modules.Navigation.Domain.NavigationItem", b =>
                {
                    b.HasOne("AdminPlatform.Modules.Navigation.Domain.NavigationMenu", null)
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_navigation_items_navigation_menus_menu_id");

                    b.HasOne("AdminPlatform.Modules.Navigation.Domain.NavigationItem", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_navigation_items_navigation_items_parent_id");
                });

            modelBuilder.Entity("AdminPlatform.Modules.Navigation.Domain.NavigationItemPermission", b =>
                {
                    b.HasOne("AdminPlatform.Modules.Navigation.Domain.NavigationItem", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_navigation_item_permissions_navigation_items_item_id");
                });

            modelBuilder.Entity("AdminPlatform.Modules.Navigation.Domain.NavigationItemSiteDetail", b =>
                {
                    b.HasOne("AdminPlatform.Modules.Navigation.Domain.NavigationItem", null)
                        .WithOne()
                        .HasForeignKey("AdminPlatform.Modules.Navigation.Domain.NavigationItemSiteDetail", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_navigation_item_site_details_navigation_items_item_id");
                });
#pragma warning restore 612, 618
        }
    }
}
